config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

resources :places, except: [:update, :edit, :destroy]
root 'places#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord

    # geocoded_by :address, :longitude => :title
    geocoded_by :address do |obj, results|
        if geo = results.first
            # puts '-------------------------------'
            # puts obj.inspect
            # puts '********'
            # puts results.inspect
            # puts [results[0].latitude, results[0].longitude].inspect
            obj.latitude = geo.latitude
            obj.longitude = geo.longitude
        end
    end
    after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

    def Place::create_place!(place_hash)
        return new(place_hash)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_google_maps_javascript_api_key

  def set_google_maps_javascript_api_key
    # Load the google maps javascript API key
    file_lines = []
    File.open('secrets.txt','r') do |f|
        f.each_line {|line| file_lines = file_lines + [line.split(':')[1].strip()]}
    end
    @javascript_maps_api_key = file_lines[2]
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    def index
        @places = Place.order('created_at DESC')
    end

    def show
        # Load the static maps API key
        file_lines = []
        File.open('secrets.txt','r') do |f|
            f.each_line {|line| file_lines = file_lines + [line.split(':')[1].strip()]}
        end
        @static_map_api_key = file_lines[1]

        @place = Place.find(params[:id])
    end

    def new
        @place = Place.new
    end

    def create
        @place = Place.create_place!(place_params)
        # @place = Place.new(place_params)
        if @place.save
            # puts"@place.latitude: " + @place.latitude.inspect
            flash[:success] = 'Place added!'
            redirect_to root_path
        else
            render 'new'
        end
    end

    private

    def place_params
        params.require(:place).permit(:title, :address, :visited_by)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Vagabond
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true

    %script(src="https://maps.googleapis.com/maps/api/js?key=#{@javascript_maps_api_key}&callback=initMap" async defer)

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body
    %h1.title Fivecircle
    #main
      - if flash[:success]
        #success.flashMessage= flash[:success]
        %p

      = link_to "Add place", new_place_path, :class => 'btn btn-primary btn-lg'

      = yield

app/views/places/_form.html.haml
= form_for @place do |f|

  = f.label :title, 'Title'
  = f.text_field :title, :class => "form-control"

  = f.label :visited_by, 'Visited by'
  = f.text_field :visited_by, :class => "form-control"

  = f.label :address, 'Address'
  = f.text_field :address, :class => "form-control"

  = f.submit 'Add!', :class => "btn btn-primary"

  = yield

.card
  .card-block
    #map

app/views/places/_place.html.haml
%li
  = link_to place.title, place_path(place)
  visited by:
  %strong #{place.visited_by}

app/views/places/index.html.haml
%h1 Places

#main
  .card
    .card-block
      %ul
        = render @places

  = yield

app/views/places/new.html.haml
%h1 Add Place
= render 'form'

app/views/places/show.html.haml
%header
  %h1=@place.title
%p
  %strong Address:
  #{@place.address}
%p
  %strong Coordinates:
  (#{@place.latitude}, #{@place.longitude})
%p
  =image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@place.latitude},#{@place.longitude}&markers=#{@place.latitude},#{@place.longitude}&zoom=16&size=640x400&key=#{@static_map_api_key}",
    :class => 'img-fluid img-rounded', :alt => "#{@place.title} on the map"